# coding: utf-8

"""


    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into model package
from .assignment import Assignment
from .assignment_date import AssignmentDate
from .assignment_override import AssignmentOverride
from .external_tool_tag_attributes import ExternalToolTagAttributes
from .lock_info import LockInfo
from .needs_grading_count import NeedsGradingCount
from .rubric_criteria import RubricCriteria
from .rubric_rating import RubricRating
from .turnitin_settings import TurnitinSettings
